.\" Manpage for dur.
.\" Contact aaditya_gnulinux@zoho.com.
.TH man 1 "30 Apr 2014" "1.1" "dur man page"
.SH NAME
dur \- A program to calculate the difference between 2 dates in days
.SH SYNOPSIS
dur <initial-date> <final-date>
.SH DESCRIPTION
Dur(ation) calculates the difference between 2 dates in days.
It takes 2 dates as arguments-

1) The initial or earlier date.
2) The final or later date.

The format used for the dates is YYYY-MM-DD.
To use the current date as one of the arguments,
command substitution can be used, like: `date +%F` or $(date +%F)

Output is the difference in number of days between the dates.
.SH EXAMPLES
.nf
dur 2013-06-13 2014-04-30
dur 2013-06-13 `date +%F`
dur `date +%F` 2015-04-25
dur 1992-02-26 $(date +%F)
.fi
.SH SEE ALSO
date(1)
.SH NOTE
For really large differences in date, example, 1901-01-01 to 2013-11-28 (41239 days),
the output maybe incorrect by a day or two, as the program was made using a simple algorithm,
not meant for complete accuracy. (error % = +- 0.0005 approx)

However, effort was made to reduce the errors to a minumum, and it should work correctly for most cases.
.SH AUTHOR
Aaditya Bagga (aaditya_gnulinux@zoho.com)